spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Desativar Kafka temporariamente para o arranque na EC2 ser limpo
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server:
  port: 8080      # Mudamos para 8080 para bater certo com o que o prof pede
  address: 0.0.0.0 # Essencial para o Docker falar com o mundo exterior

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    pt.ulusofona.productservice: DEBUG